url: "https://mochimilk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/refuge" # the subpath of your site, e.g. /blog
title: "âˆ´ ğ‘… ğ¸ ğ¹ ğ’° ğ’¢ ğ¸ âˆ´" # the name of your site, e.g. ACME Corp.
